current_fog_level = 100
froglin_id = 4
froglin_type_id = 2
old_identity = "0x2499a70183006c0eecf3b4f2c968da93a09d517fe5eded3637b004513807a4d2"
secret = "0x123"

[player]
level = 1
mana_power = 10
stash_root = "0x01"

[[player.froglins]]
attack = 8
awake_at = [60, 78, 96, 114]
defense = 4
health = 200
id = "0x01"
level = 1
stealth = 1
type_id = 1

[[player.froglins.habitats]]
coords = [[0, 0], [0, 100], [100, 0], [100, 100]]
id = "1"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins]]
attack = 0
awake_at = [0, 0, 0, 0]
defense = 0
health = 0
id = 0
level = 0
stealth = 0
type_id = 0

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins]]
attack = 0
awake_at = [0, 0, 0, 0]
defense = 0
health = 0
id = 0
level = 0
stealth = 0
type_id = 0

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins]]
attack = 0
awake_at = [0, 0, 0, 0]
defense = 0
health = 0
id = 0
level = 0
stealth = 0
type_id = 0

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins]]
attack = 0
awake_at = [0, 0, 0, 0]
defense = 0
health = 0
id = 0
level = 0
stealth = 0
type_id = 0

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.froglins.habitats]]
coords = [[0, 0], [0, 0], [0, 0], [0, 0]]
id = "0"

[[player.inventory]]
id = 0
quantity = 0

[[player.inventory]]
id = 0
quantity = 0

[[player.inventory]]
id = 0
quantity = 0

[[player.inventory]]
id = 0
quantity = 0

[[player.inventory]]
id = 0
quantity = 0
